### ISSUE TITLE
Colorful error messages

### ISSUE THREAD

**Issue by Baransu** [reasonml-community/reason-scripts#16]
Currently while stumbling upon error, messages are single color. 

<img width="646" alt="screen shot 2017-09-16 at 23 42 10" src="https://user-images.githubusercontent.com/9558691/30516234-f0c1ee24-9b38-11e7-8dfc-15e0a321338c.png">

While building using `bs-platform` from CLI error messages are nicely colored. 

<img width="604" alt="screen shot 2017-09-16 at 23 42 20" src="https://user-images.githubusercontent.com/9558691/30516233-f0be36bc-9b38-11e7-8989-cd5a5d8e7eee.png">

I was trying to find where the problem is but I don't know which part of the stack is causing it (`reason-scripts`, `bs-loader`, `react-dev-utils/WebpackDevServerUtils` or maybe `webpack`).
I would really like to work on PR bringing colors to error messages 🙂

**Comment by rrdelaney** [comment]
Hey @baransu! Thanks for opening this issue 😄

This would need to be done in the bs-loader repo. Right now bs-loader pretty much does "exec('bsb -make-world')". We would need the NodeJS "exec" call to capture the colored output from bsb and then return it to Webpack. 

It's awesome that you'd like to make a PR to fix this! I recommend checking out the bs-loader source code, and the documentation for NodeJS's child_process library

cc @chenglou

**Comment by rrdelaney** [comment]
This should be released now 😄
