### ISSUE TITLE
npm start fails on a new project created via create-react-app

### ISSUE THREAD

**Issue by loxs** [reasonml-community/reason-scripts#19]
The error I get is this:

````
./~/reason-react/lib/js/src/reasonReact.js
Module not found: Can't resolve 'bs-platform/lib/js/list.js' in '<project>/node_modules/reason-react/lib/js/src'
````

**Comment by loxs** [comment]
Ah, sorry. It works if you first run `npm install`. Though it's probably a good idea to add it to the README, az some people who are trying to use this are new to npm.

**Comment by rrdelaney** [comment]
@loxs Hm that’s weird, you shouldn’t have to run “npm install” first - I’ll look into this. 

We’re you using npm or yarn?

**Comment by loxs** [comment]
npm
