### ISSUE TITLE
Bsb error lines swallowed

### ISSUE THREAD

**Issue by chenglou** [reasonml-community/reason-scripts#21]
Finally found a repro for this:

```sh
git clone https://github.com/tiensonqin/reason-error.git
cd reason-error
npm install
npm start
```

Doesn't happen when you run `./node_modules/.bin/bsb`

**Comment by rrdelaney** [comment]
This should be fixed in the most recent beta (`reason-scripts@1.0.0-beta1`)

**Comment by chenglou** [comment]
Woah!
