### ISSUE TITLE
Sync upstream changes

### ISSUE THREAD

**Issue by InsidersByte** [reasonml-community/reason-scripts#22]
I tried to import my `package.json` so that I could access the version, however, I get the following error.

![image](https://user-images.githubusercontent.com/6938575/32888609-ba3c7534-cabf-11e7-84b6-99f16eda2832.png)

This was changed in `create-react-app` so that you can import the `package.json`, see [here](https://github.com/facebookincubator/create-react-app/blob/70e0c08ef7de8845b1a4c6700822e27e45b481a8/packages/react-scripts/config/webpack.config.dev.js#L114).

However, it seems that this is missing, see [here](
https://github.com/reasonml-community/reason-scripts/blob/master/config/webpack.config.dev.js#L118).

I am assuming that this is because upstream changes have not been merged, and not because it was removed.

**Comment by rrdelaney** [comment]
Hey, sorry I never got back to this. Right now reason-scripts is based on [bs-loader](https://github.com/reasonml-community/bs-loader). We would like to get off of this approach long-term and move to a simpler bsb-based build system, with Webpack running bsb on each file change. There is going to a larger rebase before this hits v1.0 moving to that approach.

Right now I don't have a ton of time to rebase upstream for this change, so thanks for submitting a PR 😄

**Comment by rrdelaney** [comment]
Published as `reason-scripts@next`. Can you test this out?

**Comment by InsidersByte** [comment]
Awesome 👍

Of course, I'll test it out tomorrow

**Comment by InsidersByte** [comment]
All seems to be working well

**Comment by rrdelaney** [comment]
Released in v0.8.0, should be latest on npm 😄
