### ISSUE TITLE
I am using npm and 'npm start' did not work complained of missing 

### ISSUE THREAD

**Issue by rluiten** [reasonml-community/reason-scripts#26]
I am on ubuntu 17.10.
New install of reason-cli.
Then installed bs-platform and create-react-app as in the example here.

Running `npm start` gave me the following error 
```
./node_modules/reason-react/lib/js/src/ReactDOMRe.js
Module not found: Can't resolve 'bs-platform/lib/js/caml_array.js' in '/home/rluiten/cra2/node_modules/reason-react/lib/js/src'
```

I figured out I need to do a `npm install` before the `npm start` then things worked.

Just thought I would mention it as it stumped me for 10 minutes.

**Comment by rrdelaney** [comment]
Sorry about that, I'll add a section to the README about trying an npm install if it doesn't work on the first try.

**Comment by feluxe** [comment]
I just ran into the same issue.

**Comment by rrdelaney** [comment]
Can you try using reason-scripts@beta3?

**Comment by feluxe** [comment]
Sure! I would need some info on how to install beta3 though. I tried with `npx create-react-app foo --scripts-version reason-scripts@beta3` but it doesn't work.

**Comment by rrdelaney** [comment]
Try reason-scripts@next

**Comment by feluxe** [comment]
It works with @next. Thanks!

**Comment by rrdelaney** [comment]
As soon as tests are fixed that branch will be promoted to latest 🙂
