### ISSUE TITLE
I have bs-platform installed using `yarn global add` and a newly created app doesn't recognize it

### ISSUE THREAD

**Issue by sharno** [reasonml-community/reason-scripts#31]
After I installed bs-platfrom using `yarn global add bs-platfrom` I launched the app using `yarn start` it shows me this error
```
./src/index.re
Package not found: resolving package bs-platform in /  
File "bsconfig.json", line 1
Error: package bs-platform is not found  , it is the basic package required, if you have it installed globally
Please run 'npm link bs-platform' to make it available
```

I made sure that bsb, bsc and bsrefmt are accessible through command line and they were
had to install bs-platfrom again through npm and then `npm link bs-platform` to make it work

**Comment by rrdelaney** [comment]
This is our bad - bs-platform has to be installed using npm globally rather than Yarn. I added this to the README in 81b6b7371dad4c682dd9af4cd48cabc055c7d3f0. Thanks for pointing this out!
