### ISSUE TITLE
App creation fails due to package failure?

### ISSUE THREAD

**Issue by anirudhmurali** [reasonml-community/reason-scripts#32]
![image](https://user-images.githubusercontent.com/3096325/34643107-9679813e-f344-11e7-929a-cf06fcc3f966.png)

**Comment by rrdelaney** [comment]
Ongoing issue with npm, not on our side: https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by anirudhmurali** [comment]
npm/registry#255
