### ISSUE TITLE
Some sort of configuration error?

### ISSUE THREAD

**Issue by justgage** [reasonml-community/reason-scripts#35]
After doing: `create-react-app my-create-reason-react-app --scripts-version reason-scripts`

```
> npm run start
Failed to compile.

./src/index.re
[3/4] Building src/ReasonReact.mlast
FAILED: src/ReasonReact.mlast
/usr/local/lib/node_modules/bs-platform/lib/bsc.exe -pp "/usr/local/lib/node_modules/bs-platform/lib/refmt3.exe --print binary"    -w -30-40+6+7+27+32..39+44+45+101 -nostdlib -I '/Users/justgage/code/my-create-reason-react-app/node_modules/bs-platform/lib/ocaml' -bs-no-version-header -no-alias-deps -color always -c -o src/ReasonReact.mlast -bs-syntax-only -bs-binary-ast -impl /Users/justgage/code/my-create-reason-react-app/node_modules/reason-react/src/ReasonReact.re
File "/Users/justgage/code/my-create-reason-react-app/node_modules/reason-react/src/ReasonReact.re", line 988, characters 48-50:
Error: 819: <UNKNOWN SYNTAX ERROR>
File "/Users/justgage/code/my-create-reason-react-app/node_modules/reason-react/src/ReasonReact.re", line 1:
Error: Error while running external preprocessor
Command line: /usr/local/lib/node_modules/bs-platform/lib/refmt3.exe --print binary '/Users/justgage/code/my-create-reason-react-app/node_modules/reason-react/src/ReasonReact.re' > /var/folders/qr/tdr3n25j6k32rjq1z17fy5pm0000gn/T/ocamlpp2f951e

ninja: error: rebuilding 'build.ninja': subcommand failed
Failure: /usr/local/lib/node_modules/bs-platform/lib/ninja.exe
 Location: /Users/justgage/code/my-create-reason-react-app/node_modules/reason-react/lib/bs
```

Sorry if this is something obvious 😅

**Comment by rrdelaney** [comment]
Thanks for reporting this bug!

Can you give me the following info so i can help debug the issue?

* OS version
* npm version
* BuckleScript version
* create-react-app version

Hopefully that'll help me reproduce this error :smile:

**Comment by justgage** [comment]
No problem 👍 

- OS: OSX Sierra
- NPM 5.3.0
- bsb 2.0.1 (installed globally)
- create-react-app 1.3.0

**Comment by jeffutter** [comment]
I'm running into this same issue.

NPM: 5.4.2
bsb: 2.1.0 (globally)
create-react-app: 1.5.1 (I think)

**Comment by AdamBrodzinski** [comment]
I'm *had* the same error as well (with yarn or npm) and I upgraded all of my deps except Node and that seemed to fix it (I think it might have been bsb or create react app).

OS: OSX Sierra
NPM: 5.6.0
Node: v9.6.1
BSB: 2.2.2 (globally)
cra: 1.5.2

**Comment by yoohan-dex** [comment]
have the same error !!
OS: Mac OS Sierra
yarn: 1.3.2
node: v8.9.1
bsb: 2.2.0 (globally)

**Comment by rrdelaney** [comment]
Super weird :confused: Is this on fresh installs or just happen after some time?

**Comment by yoohan-dex** [comment]
@rrdelaney it possibly from the react-reason,  I seen the same issue in that repo.

**Comment by justgage** [comment]
@rrdelaney I upgraded my versions of everything (besides OSX) and the errors seem to be gone now. I would encourage everyone to do the same

**Comment by yoohan-dex** [comment]
Yes! I can compile successfully after reinstalling all the tools.
it's an awesome project!


From yoohoo

On 6 Mar 2018, 07:20 +0800, Gage <notifications@github.com>, wrote:

@rrdelaney<https://github.com/rrdelaney> I upgraded my versions of everything (besides OSX) and the errors seem to be gone now. I would encourage everyone to do the same

**Comment by knowbody** [comment]
I started getting the same error today, tried upgrading the "tools", but still getting the error

**Comment by chenglou** [comment]
Everyone: be on bs-platform 2.2.3

**Comment by Rigellute** [comment]
I'm also experiencing this.

OS version: High Sierra 10.13.3
npm version: 5.8.0
BuckleScript version: 2.2.3

**Comment by nhducit** [comment]
I get same issue with: 

OS version: High Sierra 10.13.3
npm: 5.8.0
node: 8.11.1
BuckleScript: 2.2.3
Yarn: 1.5.1
