### ISSUE TITLE
Generate ES Modules rather than CommonJS

### ISSUE THREAD

**Issue by rhysforyou** [reasonml-community/reason-scripts#37]
Like it says in the title. There's benefits to using ES Modules over CommonJS in conjunction with tools like Webpack, mainly to do with tree shaking. It'd be great if we could make ES Modules the default for reason-scripts.

**Comment by rrdelaney** [comment]
100% agree. 1.0 will have this on by default.

**Comment by rrdelaney** [comment]
This was enabled by default in `v0.8`.
