### ISSUE TITLE
reason-react build fails if 3rd party library was built with 3.1

### ISSUE THREAD

**Issue by venil7** [reasonml-community/reason-scripts#42]
If a third party library was built with 3.1
then you add it to `reason-react` project as a dependency
then unless `npm install reason-cli@3.1.0-darwin` (notice no -g) is installed - reason-react build fails.

*temp solution*:  install `reason-cli@3.1.0` locally, but the downside is to specify architecture (`darwin`)

**Comment by rrdelaney** [comment]
Can you try this again with `reason-scripts@1.0.0-beta1`? I think I fixed the issue.
