### ISSUE TITLE
Enable namespacing in bsconfig

### ISSUE THREAD

**Issue by liubko** [reasonml-community/reason-scripts#45]
Would it make sense to add `"namespace": true` into the template?
https://bucklescript.github.io/docs/en/build-configuration.html#name-namespace

**Comment by rrdelaney** [comment]
I don't think reason-scripts apps should use `namespace`, it's mostly just for libraries.

**Comment by liubko** [comment]
IMHO adding namespace wouldn't hurt any apps, and if someone is using it for a library it will only helps

**Comment by rrdelaney** [comment]
It's currently really difficult to make a library out of an app created from `reason-scripts`, so idk how relevant  it is. If anything adding that option might be misleading.
