### ISSUE TITLE
Syntax error with fresh app

### ISSUE THREAD

**Issue by jenyckee** [reasonml-community/reason-scripts#52]
When creating a new app as described I get the following error:
```
Module build failed: /node_modules/bs-loader/index.js:84
      )
      ^

SyntaxError: Unexpected token )
```

**Comment by rrdelaney** [comment]
Hi! Could you please provide the versions of Node, Yarn, npm, CRA, and reason-scripts you are using?

**Comment by jenyckee** [comment]
node v6.11.3, yarn 1.3.2, npm 3.10.10

**Comment by rrdelaney** [comment]
It looks like you need to upgrade to at least node 8. We use trailing commas in the bs-loader codebase, which is not supported in node 6. 

https://github.com/reasonml-community/bs-loader/blob/master/packages/bs-loader/index.js

**Comment by jenyckee** [comment]
This indeed fixed it
