### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by mudrz** [reasonml-community/reason-scripts#59]
Partially Related to:
https://github.com/reasonml-community/reason-scripts/issues/50

# version 0.9 (current)
In `0.9` there is an error when running the tests:
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string`

# version beta3 (next)
- Test files with format `App_test.re` are not matched by the provided glob `**/?(*.)(spec|test).{js,jsx,mjs}`.
This glob matches `App.test.js`, but doesn't match neither `App__test.bs.js` nor `<anything>.bs.js`
Fix for the glob https://github.com/reasonml-community/reason-scripts/pull/58

- Tests don't work even if they are put in `__tests__`, because of `SyntaxError: Unexpected token import`

**Comment by anmonteiro** [comment]
Published 1.0.0-beta4 with the fix for this.
