### ISSUE TITLE
Doesn't work the first time

### ISSUE THREAD

**Issue by mcanobbio** [reasonml-community/reason-scripts#60]
Hi, I follow all these steps 

```
$ npm install -g bs-platform
$ yarn create react-app <app-name> --scripts-version reason-scripts
$ cd <app-name>
$ yarn start
```

But when I open the browser I see only a blank page, and when I open the .re files I see errors like 
`The module or file ReasonReact can't be found.` `Unbound module ReactDOMRe` `Unbound module Jest`

when ran yarn start I saw the message Compiled successfully

**Comment by rrdelaney** [comment]
Can you try using “—scripts-version reason-scripts@next”?

**Comment by mcanobbio** [comment]
Thanks, that is the solution
