### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by OlegLustenko** [reasonml-community/reason-scripts#8]
Hi !
I've made:
```bash
create-react-app <app-name> --scripts-version reason-scripts
```
and recieve error: Module not found: Can't resolve '.app' in 'C:\projects\rr\src'

Furthermore a few minutes ago I've updated bs-platform, maybe this related?

**Comment by rrdelaney** [comment]
Hi! Thanks for submitting an issue 😄 

When using reason-scripts and creating a new project it will auto-link bs-platform, maybe you could try that again? You can do that by running `npm link bs-platform` in your project's root directory.

Is the project open source? That would help me debug a bit

**Comment by OlegLustenko** [comment]
Hi, thanks for quick answer. That mistake totally depends on windows OS. I still investigate the problem maybe give feedback soon.

Totally looks like, something broken with "path".

I'll make repo and give a link soon

**Comment by rrdelaney** [comment]
Thanks for the help! I have a Windows machine I can test on with the example project, so that should make finding this a little easier 😅

**Comment by rrdelaney** [comment]
Looks like this was found in our AppVeyor builds too! Check it out: https://ci.appveyor.com/project/rrdelaney/reason-scripts/build/job/hko3akfq9hiq5sww

Might be on to something...

**Comment by OlegLustenko** [comment]
yep, seems relevant

**Comment by vinaydate** [comment]
I am facing the same issue on my Windows 10 machine (Same case as @OlegLustenko, bs-platform updated and then compilation is broken, don't know if that is related) . I did not get what does @rrdelaney wants to say by 'Might be on to something...'

And is there any solution for this? If so, let me know.

**Comment by rrdelaney** [comment]
Hi @vinaydate! I don't know if there's any work arounds or fixes right now, but reproducibility is the first step 😄 Because we can see this in our AppVeyor builds it will be a lot easier for me to try to fix! However, I'm having problems with my Windows machine and would need to fix it before looking at this...

**Comment by rrdelaney** [comment]
@OlegLustenko @vinaydate Hey folks! It looks like the underlying tooling here [bs-loader](https://github.com/reasonml-community/bs-loader) was broken on Windows in the latest release. We just published a new version of bs-loader and updated reason-scripts to use it. Everything looks good on the CI server so far!

Could you guys try using reason-scripts again?

**Comment by vinaydate** [comment]
Working, now.

**Comment by rrdelaney** [comment]
Awesome! If it still happens feel free to reopen the issue

**Comment by OlegLustenko** [comment]
Thanks works fine for me too. I have tried to debug bs-loader, but haven't enough time. 
Thanks for the fix. And nice community :)

**Comment by vinaydate** [comment]
I have a reason-scripts installation on windows machine. When the template app is run first time with yarn start, build process is thr n app runs. But after I change something in App.re, i get an error saying
```
Failed to compile.

./src/index.re
Module build failed: Error: ninja: no work to do.
ninja: no work to do.
ninja: Entering directory `lib\bs'

ninja: error: rebuilding 'build.ninja': '/mnt/g/Vinay/Projects/panchang-admin-reason/src/app_test.re', needed by 'src/app_test.mlast', miss
    at <anonymous>ule to make it
```

This `<anonymous>ule` in the last part of error is exactly what I see on console. Not a typo.

**Comment by thangngoc89** [comment]
@vinaydate you could try to run bsb -make-world

**Comment by vinaydate** [comment]
```bsb -make-world``` did not help

**Comment by rrdelaney** [comment]
@vinaydate is this for all fresh projects?

**Comment by vinaydate** [comment]
I was using a console emulator. That was the culprit for ```ninja: error```. But now, in native windows command prompt, things are not through yet.

There is an error saying

```
Module not found: You attempted to import ../../../lib/js/src/app which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

**Comment by vinaydate** [comment]
Resolved. One needs to ```npm start``` on WSL, and not on windows command console. When I did that, things seem to be working
