### ISSUE TITLE
Handle unit tests in JavaScript

### ISSUE THREAD

**Issue by scastiel** [reasonml-community/reason-scripts#9]
Because *bs-jest* is still WIP and experimental, it can be very convenient to write unit tests in JavaScript. But currently it's not possible without ejecting because it's impossible to modify the `testMatch` parameter of Jest config (in *package.json*), or *react-scripts* complains when launching tests.

I think it would be great if default `testMatch` parameter of Jest config included both `*test.re*` and `*test.js` to allow writing tests in JavaScript.

**Comment by rrdelaney** [comment]
Thanks for submitting a PR to fix this! It should be released now in v0.6.7 😄
